import type { Metadata } from "next";
import { Roboto, Ubuntu } from "next/font/google";
import "../styles/globals.css";
import { AppProviders } from "../components/providers/AppProviders";
import PrimaryHeader from "@/components/layout/header/PrimaryHeader";
import PrimaryFooter from "@/components/layout/footer/PrimaryFooter";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${ubuntu.variable}`}>
      <body className="antialiased">
        <AppProviders>
          <PrimaryHeader />
          {children}
          <PrimaryFooter />
        </AppProviders>
      </body>
    </html>
  );
}
